export const GENRES = [
    { label: "Fantasy", slug: "fantasy" },
    { label: "Science Fiction", slug: "science_fiction" },
    { label: "Mystery", slug: "mystery" },
    { label: "Historical Fiction", slug: "historical_fiction" },
    { label: "Romance", slug: "romance" },
    { label: "Horror", slug: "horror" },
    { label: "Adventure", slug: "adventure" },
    { label: "Literary Fiction", slug: "literary_fiction" },
    { label: "Young Adult", slug: "young_adult" },
    { label: "Dystopian", slug: "dystopian" },
    { label: "Biography", slug: "biography" },
    { label: "Self-Help", slug: "self_help" },
    { label: "History", slug: "history" },
    { label: "Politics", slug: "politics" },
    { label: "Science", slug: "science" },
    { label: "Psychology", slug: "psychology" },
    { label: "Philosophy", slug: "philosophy" },
    { label: "Business", slug: "business" },
    { label: "Health", slug: "health" },
    { label: "True Crime", slug: "true_crime" },
    { label: "Cookbooks", slug: "cooking" },
    { label: "Art", slug: "art" },
    { label: "Travel", slug: "travel" },
    { label: "Religion", slug: "religion" },
];
export const CATEGORIES = [
    { label: "Fantasy", key: "fantasy" },
    { label: "Science Fiction", key: "science_fiction" },
    { label: "Mystery & Thriller", key: "mystery" },
    { label: "Historical Fiction", key: "historical_fiction" },
    { label: "Romance", key: "romance" },
    { label: "Horror", key: "horror" },
    { label: "Adventure", key: "adventure" },
    { label: "Literary Fiction", key: "literary_fiction" },
    { label: "Young Adult (YA) Fiction", key: "young_adult" },
    { label: "Dystopian", key: "dystopian" },
    { label: "Biography & Memoir", key: "biography" },
    { label: "Self-Help", key: "self_help" },
    { label: "History", key: "history" },
    { label: "Politics & Current Affairs", key: "politics" },
    { label: "Science & Nature", key: "science" },
    { label: "Psychology", key: "psychology" },
    { label: "Philosophy", key: "philosophy" },
    { label: "Business & Economics", key: "business" },
    { label: "Poetry", key: "poetry" },
    { label: "Comics & Graphic Novels", key: "graphic_novels" },
    { label: "Art & Photography", key: "art" },
    { label: "Cooking & Food", key: "cooking" },
    { label: "Crafts & Hobbies", key: "crafts_and_hobbies" },
    { label: "Travel", key: "travel" },
    { label: "Parenting & Families", key: "parenting" },
    { label: "Education", key: "education" },
    { label: "Health & Fitness", key: "health" },
    { label: "Spirituality & Religion", key: "religion" },
    { label: "True Crime", key: "true_crime" },
    { label: "Humor", key: "humor" },
    { label: "Technology", key: "technology" },
    { label: "Engineering", key: "engineering" },
];
export const SHELF_STATUSES = [
    { value: "want", label: "Want to Read" },
    { value: "reading", label: "Currently Reading" },
    { value: "read", label: "Read" },
];
